#!/bin/bash

# ALIASES
alias l="ls -ltra | grep -i "
alias python=python3


# attach or create a tmux session named..
function tm-ca () {
        tmux attach -d -t $1 || tmux new -s $1
}

function ssh-dwhdwh () {
	ssh datawarehouse@datawarehouse.internal.vikingco.com
}

function ssh-hojerdwh () {
        ssh jeroen.houben@datawarehouse.internal.vikingco.com
}

function sqlc() {
	psql -d datawarehouse -t -c "$1"
}


function writeTabColsOfSchema () {
	echo Each table goes to file : table.cols
	for table in $(sqlc "select table_name from information_schema.tables where table_schema='$1'"); do
		outfile=$(echo $table | tr '[:upper:]' '[:lower:]').cols
		sqlc "select column_name from INFORMATION_SCHEMA.COLUMNS where table_name ='$table' and table_schema='$1'" > $outfile
	done
}

function writeCsvCols() {
	mkdir -p ./csvCols
	for csv in $(echo *.csv); do
		lowerCsv=$(echo $csv | tr '[:upper:]' '[:lower:]')
		table=${lowerCsv%.*};	# deletes shortest possible '*.' from the right
		header=$(head -1 $csv)
		utfToAsciiHeader=$(echo $header| uconv -f UTF-8 -t ASCII --remove-signature)
		echo $utfToAsciiHeader | tr '[:upper:]' '[:lower:]'| sed -e 's/,/\n/g' > ./csvCols/csv.$table.cols
	done
}

function diffFiles() {
	for csvfile in $(echo ${1}*); do
		dbfile=${csvfile#$1}
		echo "****** diff $dbfile -> $csvfile ******"
		diff -w -B $dbfile $csvfile
	done
}

