#!/bin/bash

## PATH
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

## EXPORT VARIABLES
export myFunctions="~/git/huuubsenv/functions"

# ALIASES
alias l="ls -ltra | grep -i "
alias python=python3

## FUNCTIONS
# attach or create a tmux session named..
function tm-ca () {
        tmux attach -d -t $1 || tmux new -s $1
}

function ssh-dwhdwh () {
	ssh datawarehouse@datawarehouse.internal.vikingco.com
}

function ssh-hojerdwh () {
        ssh jeroen.houben@datawarehouse.internal.vikingco.com
}

function sqlc() {
	psql -d datawarehouse -t -c "$1"
}


function writeTabColsOfSchema () {
	echo Each table goes to file : table.cols
	for table in $(sqlc "select table_name from information_schema.tables where table_schema='$1'"); do
		outfile=$(echo $table | tr '[:upper:]' '[:lower:]').cols
		sqlc "select column_name from INFORMATION_SCHEMA.COLUMNS where table_name ='$table' and table_schema='$1'" > $outfile
	done
}

function writeCsvCols() {
	mkdir -p ./csvCols
	for csv in $(echo *.csv); do
		lowerCsv=$(echo $csv | tr '[:upper:]' '[:lower:]')
		table=${lowerCsv%.*};	# deletes shortest possible '*.' from the right
		header=$(head -1 $csv)
		utfToAsciiHeader=$(echo $header| uconv -f UTF-8 -t ASCII --remove-signature)
		echo $utfToAsciiHeader | tr '[:upper:]' '[:lower:]'| sed -e 's/,/\n/g' > ./csvCols/csv.$table.cols
	done
}

function diffFiles() {
	for csvfile in $(echo ${1}*); do
		dbfile=${csvfile#$1}
		echo "****** diff $dbfile -> $csvfile ******"
		diff -w -B $dbfile $csvfile
	done
}

## JIM RELATED
Function RecrJimSchemaAndStartJim2PG () {
        echo "We will 1. Recreate the schema of jim_sbss_replica, 2. drop current_file.txt (to be able to load it again) and 3. start the load again"
        readonly CodeDir=/data/programs/jimbbs2pg/code/
        psql -d datawarehouse -a -f $CodeDir/drop_foreign_key_constraints.sql
        psql -d datawarehouse -a -f $CodeDir/create_jim_sbss_replica_tables.sql
        rm $CodeDir/../data/latest_processed_file.txt
        $CodeDir/jimbbs2pg.sh
}

