#!/bin/bash -e

## ALIASES
alias l="ls -ltra | grep -i"
alias vi=vim
alias pp='python -mjson.tool'
alias suroot='sudo -E -s'
alias ltr="ls -ltra"
alias tf='tail -f'
alias sr='screen -r'
alias vimyfunctions='vi $HOME/GIT/huuubsenv/env/functions'

alias asalp="autoscreen jeroen@192.168.1.2"
alias asalpnet="autoscreen alpnet"
alias astkaf="autoscreen pi@tkafeeke"

alias mvlog="/home/datawarehouse/GIT/metrics-dwh-programs/sbss/log/mv"
alias jimlog="/home/datawarehouse/GIT/metrics-dwh-programs/sbss/log/jim"
alias stlog="/home/datawarehouse/GIT/metrics-dwh-programs/sbss/log/stievie"
alias sbss="/home/datawarehouse/GIT/metrics-dwh-programs/sbss"
alias sshRouter="ssh -L 1800:192.168.1.1:8080 alpnet"
