#!/bin/bash -e 

## EXPORT VARIABLES
export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=vim
export VISUAL=vim #edit command from prompt in vim (command mode v)
